language: julia
os:
  - linux
  - osx

julia:
  - 1.0
  - 1.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: 1.0
    - julia: nightly

notifications:
  email: false

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git libxml2-dev r-base r-base-dev r-recommended -y --allow-unauthenticated; fi
  
  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg R-*.pkg -target /; fi

  # both
  - sudo R -e 'install.packages(c("ape", "rdiversity"), repos="http://cran.r-project.org")'

after_success:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); Pkg.add("Documenter")'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then julia --color=yes -e 'using Coverage; p = process_folder(); Coveralls.submit(p); Codecov.submit(p)'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then julia --color=yes -e 'include(joinpath("docs", "make.jl"))'; fi
