language: julia

notifications:
  recipients:
    - git@richardreeve.net
  email:
    on_success: change
    on_failure: always

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - openssl aes-256-cbc -K $encrypted_b827f4fd7e05_key -iv $encrypted_b827f4fd7e05_iv -in doc/.documenter.enc -out doc/.documenter -d

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Diversity", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Diversity", "test")); include("coverage.jl")'
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("Diversity")); include(joinpath("doc", "make.jl"))'
