language: julia

notifications:
  recipients:
    - git@richardreeve.net
  email:
    on_success: change
    on_failure: always

os:
  - linux
  - osx

julia:
  - 0.6
  - 1.0
  - 1.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git libxml2-dev r-base r-base-dev r-recommended -y --allow-unauthenticated; fi

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then JULIA_MUST_CROSSVALIDATE=1 julia -e '(try using Pkg; true catch; false end || Pkg.init()); Pkg.clone(pwd()); Pkg.build("Diversity"); Pkg.test("Diversity", coverage=true)'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then julia -e '(try using Pkg; true catch; false end || Pkg.init()); Pkg.clone(pwd()); Pkg.build("Diversity"); Pkg.test("Diversity", coverage=true)'; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then julia -e '(try using Pkg; true catch; false end || Pkg.init()); Pkg.clone(pwd()); Pkg.build("Diversity"); Pkg.test("Diversity", coverage=true)'; fi

after_success:
  - julia -e '(try using Pkg; catch end); using Diversity; cd(Diversity.path()); include("coverage.jl")'
  - julia -e '(try using Pkg; catch end); Pkg.add("Documenter"); using Diversity; cd(Diversity.path(;dir=".")); include(joinpath("docs", "make.jl"))'
