name: Documentation

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
          arch: x64
      - uses: julia-actions/cache@v3
      - name: Install dependencies
        run: |
          import Pkg
          Pkg.develop(Pkg.PackageSpec(path=pwd()))
          Pkg.instantiate()
        shell: julia --project=docs --color=yes {0}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
