name: CI

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:

jobs:
  diversity-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        julia-version:
          - '1.8'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        R-version:
          - 'release'
        arch:
          - x64
        experimental:
          - false
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - name: Install R
      if: matrix.os == 'ubuntu-latest'
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R-version }}
    - name: Install ape, vegan and rdiversity
      if: matrix.os == 'ubuntu-latest'
      run: |
        install.packages("ape", repos="http://cran.r-project.org")
        install.packages("vegan", repos="http://cran.r-project.org")
        install.packages("rdiversity", repos="http://cran.r-project.org")
      shell: R --vanilla --file={0}
    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
    - name: Running
      uses: julia-actions/julia-runtest@v1
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Codecov
      uses: codecov/codecov-action@v3
